### ISSUE TITLE
Modernise dataset template

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldfbench#95]
In the dataset templates we should use a `pyproject.toml`-based approach (rather than `setup.py`). Something along the lines of this seems to work:
```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cldfbench_languageatlasofthepacificarea"
version = "2.0"
dependencies = [
    'cldfbench',
    'pyglottolog',
    'fiona',
    'shapely',
    'cldfgeojson',
    'mako',
    'matplotlib',
    'tqdm',
]

[tool.setuptools]
packages = ["lib", "laotpa_commands"]
py-modules = ["cldfbench_languageatlasofthepacificarea"] # dash, not underscore

[project.optional-dependencies]
test = ['pytest-cldf']

[project.entry-points."cldfbench.dataset"]
languageatlasofthepacificarea = 'cldfbench_languageatlasofthepacificarea:Dataset'

[project.entry-points.'cldfbench.commands']
laotpa = 'laotpa_commands'
```
